- name: set grub password
  lineinfile:
    path: /etc/grub.d/40_custom
    regexp: "{{ item.key }}"
    line: "{{ item.key }}{{ item.value }}"
    state: present
  with_items:
    - key: "set superusers="
      value: '"{{ grub_user }}"'
    - key: "password_pbkdf2 "
      value: "{{ grub_user }} {{ grub_pwdhash }}"
  register: grub_pwd
  when: set_grub_bootpwd and os_type != "server"
  tags:
    - boot

- name: modify grub defaults
  lineinfile:
    path: /etc/default/grub
    regexp: "(^|^#){{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
    state: present
  with_items:
    - key: "GRUB_TIMEOUT"
      value: "10"
    - key: "GRUB_TIMEOUT_STYLE"
      value: "hidden"
  register: grub_defaults
  tags:
    - boot

- name: update grub
  shell: update-grub
  when: grub_pwd.changed or grub_defaults.changed
  tags:
    - boot
