- name: set grub password
  lineinfile:
    path: /etc/grub.d/40_custom
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "set superusers"
      line: 'set superusers="{{ grub_user }}"'
    - regexp: "password_pbkdf2"
      line: "password_pbkdf2 {{ grub_user }} {{ grub_pwdhash }}"
  register: grub_pwd
  when: grub_bootpwd and os_type != "server"
  tags:
    - boot

- name: modify grub defaults
  lineinfile:
    path: /etc/default/grub
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "(^$|#)GRUB_TIMEOUT"
      line: "GRUB_TIMEOUT=10"
    - regexp: "(^$|#)GRUB_TIMEOUT_STYLE"
      line: "GRUB_TIMEOUT_STYLE=hidden"
  register: grub_defaults
  tags:
    - boot

- name: update grub
  shell: update-grub
  when: grub_pwd.changed or grub_defaults.changed
  tags:
    - boot
