- name: installing mail utilities
  apt:
    pkg:
      - mailutils
    state: present
    update_cache: yes
  tags:
    - mailing

- name: shell - set MAIL variable for all users
  lineinfile:
    path: /etc/profile.d/mail.sh
    line: "export MAIL=$HOME/Maildir/"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
  tags:
    - mailing

- name: load users
  include_vars: users.yml
  when: localmail
  tags:
    - mailing

- name: set admin mail on local
  set_fact:
    mail_dest: "root@localhost"
    mail_root_fwd: "{{ item.name }}@localhost"
  when: ({{ localmail }}) and ({{ item.chief }}) and "{{ item.state }}" == "present"
  with_items:
    - "{{users_admin}}"
  tags:
    - mailing

- name: set admin mail on external
  set_fact:
    mail_dest: "{{ extmail_addr }}"
    mail_root_fwd: "{{ extmail_addr }}"
  when: not localmail
  tags:
    - mailing

- name: system - create mail forwarding from root to major administrative user
  lineinfile:
    path: /root/.forward
    create: yes
    mode: 640
    owner: root
    group: root
    line: "{{ mail_root_fwd }}"
    state: present
  tags:
    - mailing
